// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VeriTestAPI.Models;

#nullable disable

namespace VeriTestAPI.Migrations
{
    [DbContext(typeof(MyContext))]
    partial class MyContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VeriTestAPI.Models.Harcama", b =>
                {
                    b.Property<int>("HarcamaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HarcamaId"));

                    b.Property<int?>("MusteriId")
                        .HasColumnType("int");

                    b.Property<bool>("OdenmeDurumu")
                        .HasColumnType("bit");

                    b.Property<float>("Tutar")
                        .HasColumnType("real");

                    b.HasKey("HarcamaId");

                    b.HasIndex("MusteriId");

                    b.ToTable("Harcamalar");
                });

            modelBuilder.Entity("VeriTestAPI.Models.Musteri", b =>
                {
                    b.Property<int>("MusteriId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MusteriId"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MusteriId");

                    b.ToTable("Musteriler");
                });

            modelBuilder.Entity("VeriTestAPI.Models.Harcama", b =>
                {
                    b.HasOne("VeriTestAPI.Models.Musteri", "Musteri")
                        .WithMany("Harcamalar")
                        .HasForeignKey("MusteriId");

                    b.Navigation("Musteri");
                });

            modelBuilder.Entity("VeriTestAPI.Models.Musteri", b =>
                {
                    b.Navigation("Harcamalar");
                });
#pragma warning restore 612, 618
        }
    }
}
